### ISSUE TITLE
Expose `TextEditOutput`?

### ISSUE THREAD

**Issue by eswartz** [p4ymak/egui_code_editor#2]
I'm happy with the ease of use for `CodeEditor` to provide syntax highlighting and such for `TextEdit`, but it'd be better if `CodeEditor::show(Ui)` returned `TextEditOutput` instead of `Response`. I need to use the various fields of the edit state for other purposes.

(I tried this locally, but then it breaks `Ui::add(CodeEditor...:show())` since egui wants several other traits to be defined... not sure how you'd want to resolve this.)

**Comment by p4ymak** [comment]
Hello and thanks for your recommendation!
Published new version on [crates.oi](https://crates.io/crates/egui_code_editor)

**Comment by p4ymak** [comment]
@eswartz 

Hello and thanks for your recommendation!
Published new version on [crates.oi](https://crates.io/crates/egui_code_editor)
